### ISSUE TITLE
this is really amazing work !

### ISSUE THREAD

**Issue by 4eayx** [S3NEO/android_vendor_samsung_s3ve3g_sony#7]
...this is really rEAlly REALLY amazing work !!!!!!     ! Thanks ! 

... there is just a tiny hickup issue with the cell data connection not coming up in _ 15.1_ !

up on activating cellular data the interface rmnet0 is not coming up and dose not obtain an ip adress. 

And after adb shell :  ifconfig rmnet0 up the interface is up but the dhcptool dose not seam to be able to obtain a dhcp lease ...
... any ideas ???

**Comment by PythonLimited** [comment]
Yes that's what I'm currently looking after. Which kernel u use BTW?

**Comment by PythonLimited** [comment]
it is fixed in the more recent releases btw
